#!/usr/bin/env python3
"""Generate an AgentCore harness for each agent in this team.

    python3 build_harnesses.py           # write app/<name>/ and update agentcore.json
    python3 build_harnesses.py --check   # fail if the generated files are stale

The five runtimes remain the real team — see README. These harnesses exist so
each agent also appears as a managed harness resource, and they are generated
rather than hand-written so a change to a role's tactics reaches both.

What a harness cannot do is listed in lib/harness_prompt.HARNESS_CAVEATS and
repeated in each generated system-prompt.md.
"""

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
sys.path.insert(0, str(ROOT.parent / "lib"))

from test_helpers import mock_agentcore  # noqa: E402

mock_agentcore()

from harness_prompt import HARNESS_CAVEATS, build  # noqa: E402

# (agent dir, harness name, model) — the model matches the runtime's.
AGENTS = [
    ("ai-gk", "ai_gk_harness", "us.amazon.nova-lite-v1:0"),
    ("ai-def", "ai_def_harness", "us.amazon.nova-lite-v1:0"),
    ("ai-ml", "ai_ml_harness", "us.amazon.nova-micro-v1:0"),
    ("ai-mr", "ai_mr_harness", "us.amazon.nova-micro-v1:0"),
    ("ai-fwd", "ai_fwd_harness", "us.amazon.nova-pro-v1:0"),
]

# One model call per tick. A football tick is a reflex, not a research task, so
# there is nothing for a multi-iteration loop to do.
MAX_ITERATIONS = 1
TIMEOUT_SECONDS = 15


def load_agent(agent_dir: str):
    path = ROOT / agent_dir / "src" / "main.py"
    sys.path.insert(0, str(path.parent))
    spec = importlib.util.spec_from_file_location(f"h_{agent_dir.replace('-', '_')}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render(agent_dir: str, harness_name: str, model_id: str):
    mod = load_agent(agent_dir)
    caveats = "\n".join(f"- {c}" for c in HARNESS_CAVEATS)
    header = (
        f"<!-- Generated by build_harnesses.py from {agent_dir}/src/main.py. Do not edit. -->\n\n"
        "# Harness build\n\n"
        "This is the harness form of this agent. Relative to the runtime version it has:\n\n"
        f"{caveats}\n\n"
    )
    prompt = header + build(mod.ROLE, mod.MY_PLAYER_ID, mod.SYSTEM_PROMPT)
    spec = {
        "name": harness_name,
        "model": {"provider": "bedrock", "modelId": model_id},
        "tools": [],
        "skills": [],
        "memory": {"mode": "disabled"},
        "maxIterations": MAX_ITERATIONS,
        "timeoutSeconds": TIMEOUT_SECONDS,
    }
    return spec, prompt


def main():
    check = "--check" in sys.argv
    stale = []

    config_path = ROOT / "agentcore" / "agentcore.json"
    config = json.loads(config_path.read_text())
    entries = []

    for agent_dir, harness_name, model_id in AGENTS:
        spec, prompt = render(agent_dir, harness_name, model_id)
        out_dir = ROOT / "app" / harness_name
        spec_text = json.dumps(spec, indent=2) + "\n"

        for name, text in (("harness.json", spec_text), ("system-prompt.md", prompt)):
            target = out_dir / name
            current = target.read_text() if target.exists() else None
            if current != text:
                stale.append(str(target.relative_to(ROOT)))
                if not check:
                    out_dir.mkdir(parents=True, exist_ok=True)
                    target.write_text(text)

        entries.append({"name": harness_name, "path": f"app/{harness_name}"})
        if not check:
            print(f"  {harness_name:16s} {model_id:28s} {len(prompt):5d} chars of prompt")

    if config.get("harnesses") != entries:
        stale.append("agentcore/agentcore.json")
        if not check:
            config["harnesses"] = entries
            config_path.write_text(json.dumps(config, indent=2) + "\n")

    if check:
        if stale:
            print("Stale harness files — run `python3 build_harnesses.py`:")
            for s in stale:
                print(f"  - {s}")
            return 1
        print("Harness files are up to date.")
        return 0

    print(f"\nWrote {len(AGENTS)} harnesses and updated agentcore/agentcore.json.")
    print("Deploy them with the runtimes:  AWS_DEFAULT_REGION=us-east-1 python3 deploy_all.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
